/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_luminousmossboss_luminous_Detector */

#ifndef _Included_com_luminousmossboss_luminous_Detector
#define _Included_com_luminousmossboss_luminous_Detector
#ifdef __cplusplus
extern "C" {
#endif

JNIEXPORT bool JNICALL Java_com_luminousmossboss_luminous_Detector_isSilene
    (JNIEnv * env, jobject obj, jstring flower_xml, jstring vocab_xml, jstring silene_xml, jint height, jint width, jbyteArray img_array);

#ifdef __cplusplus
}
#endif
#endif
